apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  source:
    path: manifests/argocd
    repoURL: https://github.com/satoruh/isle/
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
