apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
- base/namespace.yaml
- https://github.com/argoproj/argo-cd/manifests/cluster-install?ref=stable

patches:
- path: overlays/argocd-cm.yaml
- target:
    version: v1
    kind: Service
    name: argocd-server
  patch: |-
    - op: add
      path: /spec/type
      value: LoadBalancer
    - op: add
      path: /metadata/annotations/service.beta.kubernetes.io~1oci-load-balancer-shape
      value: flexible
    - op: add
      path: /metadata/annotations/service.beta.kubernetes.io~1oci-load-balancer-shape-flex-min
      value: "10"
    - op: add
      path: /metadata/annotations/service.beta.kubernetes.io~1oci-load-balancer-shape-flex-max
      value: "10"
